"""Add AppSetting table and review_status fields

Revision ID: 3c3e26449556
Revises: b3a5615e6067
Create Date: 2026-05-05 07:13:34.197790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3e26449556'
down_revision: Union[str, Sequence[str], None] = 'b3a5615e6067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_app_settings_key'))
    )

    with op.batch_alter_table('processed_lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('needs_geo_check', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_processed_lots_needs_geo_check'), ['needs_geo_check'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_lots_needs_geo_check'))
        batch_op.drop_column('needs_geo_check')
        batch_op.drop_column('review_status')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
