"""add investment fields

Revision ID: b3a5615e6067
Revises: 51d0f7f8f001
Create Date: 2026-05-05 04:47:12.936428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b3a5615e6067'
down_revision: Union[str, Sequence[str], None] = '51d0f7f8f001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_audit_logs")
    
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('payload')

    with op.batch_alter_table('lot_event_subscriptions', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey') # Removed because of missing name
        batch_op.create_foreign_key('fk_les_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('last_notified_at')

    with op.batch_alter_table('lot_geo_snapshots', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_lgs_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lot_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False, server_default=''))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_ln_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('body')
        batch_op.drop_column('pinned')

    with op.batch_alter_table('lot_price_events', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_lpe_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lot_status_events', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_lse_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lot_workflow_states', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_lws_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('processed_lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_name', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('property_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_area_gba', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gla', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('land_area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('floors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_built', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occupancy_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('anchor_tenants', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monthly_fixed_rent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_variable_rent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_other_income', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_opex', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noi_annual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('legal_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encumbrances', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('land_risk_flag', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('technical_condition', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('power_kw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parking_spaces', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_processed_lots_discount_percent'), ['discount_percent'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_lots_needs_human_review'), ['needs_human_review'], unique=False)
        # batch_op.drop_constraint(batch_op.f('fk_processed_lots_duplicate_of'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pl_duplicate_of', 'processed_lots', ['duplicate_of_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_params', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('filters')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_search_id'), ['search_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_s_search_id', 'saved_searches', ['search_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('target_id')
        batch_op.drop_column('last_notified_at')
        batch_op.drop_column('saved_search_id')

    with op.batch_alter_table('valuation_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_valuation_runs_content_hash'), ['content_hash'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_vr_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('watchlist_lots', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_wl_watchlist_id', 'watchlists', ['watchlist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_wl_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_watchlists_lot_id'), ['lot_id'], unique=False)
        batch_op.create_foreign_key('fk_w_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('workflow_tasks', schema=None) as batch_op:
        batch_op.alter_column('task_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_wt_lot_id', 'processed_lots', ['lot_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])
        batch_op.alter_column('task_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_watchlists_lot_id'))
        batch_op.drop_column('lot_id')

    with op.batch_alter_table('watchlist_lots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'watchlists', ['watchlist_id'], ['id'])
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('valuation_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_valuation_runs_content_hash'))
        batch_op.drop_column('content_hash')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_search_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_notified_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'saved_searches', ['saved_search_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_subscriptions_search_id'))
        batch_op.drop_column('search_id')

    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filters', sqlite.JSON(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('query_params')

    with op.batch_alter_table('processed_lots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_processed_lots_duplicate_of'), 'processed_lots', ['duplicate_of_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_processed_lots_needs_human_review'))
        batch_op.drop_index(batch_op.f('ix_processed_lots_discount_percent'))
        batch_op.drop_column('parking_spaces')
        batch_op.drop_column('power_kw')
        batch_op.drop_column('technical_condition')
        batch_op.drop_column('land_risk_flag')
        batch_op.drop_column('encumbrances')
        batch_op.drop_column('legal_status')
        batch_op.drop_column('noi_annual')
        batch_op.drop_column('monthly_opex')
        batch_op.drop_column('monthly_other_income')
        batch_op.drop_column('monthly_variable_rent')
        batch_op.drop_column('monthly_fixed_rent')
        batch_op.drop_column('anchor_tenants')
        batch_op.drop_column('occupancy_rate')
        batch_op.drop_column('year_built')
        batch_op.drop_column('floors')
        batch_op.drop_column('land_area')
        batch_op.drop_column('gla')
        batch_op.drop_column('total_area_gba')
        batch_op.drop_column('property_type')
        batch_op.drop_column('object_name')

    with op.batch_alter_table('lot_workflow_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('lot_status_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('lot_price_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('lot_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])
        batch_op.drop_column('content')

    with op.batch_alter_table('lot_geo_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('lot_event_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_notified_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'processed_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sqlite.JSON(), nullable=True))
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('metadata_json')

    op.create_table('_alembic_tmp_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
