"""sync_schema

Revision ID: da29e0ae9131
Revises: c7584aa7a902
Create Date: 2026-04-16 22:08:28.774211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da29e0ae9131'
down_revision: Union[str, Sequence[str], None] = 'c7584aa7a902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deal_of_the_week', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_processed_lots_duplicate_of_id'), ['duplicate_of_id'], unique=False)
        batch_op.create_foreign_key('fk_processed_lots_duplicate_of', 'processed_lots', ['duplicate_of_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('processed_lots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_processed_lots_duplicate_of', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_processed_lots_duplicate_of_id'))
        batch_op.drop_column('duplicate_of_id')
        batch_op.drop_column('is_deal_of_the_week')
